name: dotnet-roslyn-dynamic-api

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        command: build
        containerRegistry: dockerHub
        repository: thbst16/dotnet-roslyn-dynamic-api
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push the image to Dockerhub
      inputs:
       command: push
       containerRegistry: dockerHub
       repository: thbst16/dotnet-roslyn-dynamic-api
       tags: |
         $(Build.BuildId)
         latest