name: dotnet-roslyn-dynamic-api

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        command: build
        containerRegistry: dockerHub
        repository: thbst16/dotnet-roslyn-dynamic-api
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push the image to Dockerhub
      inputs:
       command: push
       containerRegistry: dockerHub
       repository: thbst16/dotnet-roslyn-dynamic-api
       tags: |
         $(Build.BuildId)
         latest

- stage: Deploy
  displayName: Deploy docker container
  dependsOn: Build
  jobs:

  - job: Deploy
    displayName: Deploy the container to Azure Web App using Docker Compose
    steps:
    - task: CmdLine@2
      inputs:
        script: dir
        workingDirectory: $(workingDirectory) 
    - task: AzureWebAppContainer@1
      displayName: Deploy the docker image
      inputs:
        azureSubscription: becksAzure
        appName: dotnet-roslyn-dynamic-api
        multicontainerConfigFile: $(workingDirectory)/docker-compose.yml