## @host = http://localhost:5001
@host = https://dotnet-roslyn-dynamic-api.azurewebsites.net/
@contentType = application/json

GET {{host}}/api/entity HTTP/1.1

###

POST {{host}}/api/entity/3fa85f64-5717-4562-b3fc-2c963f66affe HTTP/1.1
Content-Type: {{contentType}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66affe",
  "name": "Computer",
  "fields": "public Guid Id { get; set; } public string Name { get; set; } public string IpAddress {get; set;}",
  "isActive": true
}

###

GET {{host}}/api/Computer HTTP/1.1

###

POST {{host}}/api/Computer/3fa85f64-5717-4562-b3fc-2c963f66afad HTTP/1.1
Content-Type: {{contentType}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afad",
  "name": "My computer",
  "ipAddress": "122.22.311.12"
}

###

GET {{host}}/api/album HTTP/1.1

###

POST {{host}}/api/album/3fa85f64-5717-4562-b3fc-2c963f66afa6 HTTP/1.1
Content-Type: {{contentType}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "title": "Album 1",
  "artist": "Artist 1",
  "tracks": 7
}

###

GET {{host}}/api/book HTTP/1.1

###

POST {{host}}/api/book/3fa85f64-5717-4562-b3fc-2c963f66afa7 HTTP/1.1
Content-Type: {{contentType}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa7",
  "title": "Book 1",
  "author": "Author 1"
}